source("https://bioconductor.org/biocLite.R")
biocLite('pathview', suppressUpdates=TRUE, siteRepos=c('http://cran.us.r-project.org'))
biocLite('KEGGREST', suppressUpdates=TRUE, siteRepos=c('http://cran.us.r-project.org'))
biocLite("clusterProfiler", suppressUpdates=TRUE, siteRepos=c('http://cran.us.r-project.org'))
# biocLite("GSEABase", suppressUpdates=TRUE, siteRepos=c('http://cran.us.r-project.org'))
